name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: fullstack-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Login by ssh
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}
        USERNAME: ${{ secrets.USERNAME }}
        HOSTNAME: ${{secrets.HOSTNAME }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key ${USERNAME}@${HOSTNAME}

    - name: Pull docker image
      run: |
        sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: kill previous container
      run: |
        sudo docker kill $CONTAINER_NAME

    - name: start container
      run: |
        sudo docker run -d -p 8000:8000 --name $CONTAINER_NAME $REGISTRY/$REPOSITORY:$IMAGE_TAG